[phases.setup]
nixPkgs = ["nodejs_20", "python3", "python3Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "ln -sf $(which python3) /usr/bin/python",
  "pip3 install yt-dlp",
  "npm install"
]

[start]
cmd = "node index.js"
